import styles from '@/styles/Home.module.css'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useState } from 'react'

export default function Home({connectedAddress}: {connectedAddress: string}) {
  
  return (
    <>
      <Head>
        <title>Pawnify</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className='p-4 flex justify-center items-center'>
          <div>
            <p className='text-center text-3xl'> Welcome to Pawnify </p>
            <div className='flex justify-center items-center'>
              <Link href='/borrow' className='m-2 px-4 py-3 text-gray-600 bg-gray-50 border border-gray-50 focus:outline-none focus:bg-gray-100 hover:bg-gray-100 duration-100 cursor-pointer text-xl leading-3 font-normal'> Borrow </Link>
              <Link href='/lend' className='m-2 px-4 py-3 text-gray-600 bg-gray-50 border border-gray-50 focus:outline-none focus:bg-gray-100 hover:bg-gray-100 duration-100 cursor-pointer text-xl leading-3 font-normal'> Lend </Link>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
