import styles from '@/styles/Home.module.css'
import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import Lend from '../component/Lend'

export default function lend({connectedAddress}: {connectedAddress: string}) {
  
  return (
    <>
      <Head>
        <title>Pawnify</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className='p-4'>
          <Lend connectedAddress={connectedAddress} />
        </div>
      </main>
    </>
  )
}
